### ISSUE TITLE
OrcaSlicer for Apple Silicon - 'The Application OrcaSlicer" can't be opened'

### ISSUE THREAD

**Issue by chadwallacehart** [tinymachines3d/Slicer#1]
I cloned your https://github.com/tinymachines3d/Slicer repo and I am trying to run OrcaSlicer_V1.6.3_Mac_AppleSilicon_signed_TM3D, but it is giving me a 'The Application OrcaSlicer" can't be opened'.

I can run the original SoftFever version here: https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.6.3, so I think it is something with the build here.

I also submitted this to the Tiny Machines Freshdesk (#66969)

**Comment by tinymachines3d** [comment]
Seems like this was a github server issue at the time.
